# Generated by Django 3.1.4 on 2021-01-07 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0004_info_user_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=500)),
                ('come_message', models.CharField(max_length=500)),
                ('go_message', models.CharField(max_length=500)),
                ('come_message_date', models.DateTimeField(auto_now_add=True)),
                ('go', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesaj', to=settings.AUTH_USER_MODEL, verbose_name='mesaj')),
            ],
        ),
    ]
